/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMyPassesRouteImport } from './routes/_authenticated/my-passes'
import { Route as AuthenticatedVolunteerDashboardRouteImport } from './routes/_authenticated/volunteer-dashboard'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPassesRoute = AuthenticatedMyPassesRouteImport.update({
  id: '/my-passes',
  path: '/my-passes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVolunteerDashboardRoute =
  AuthenticatedVolunteerDashboardRouteImport.update({
    id: '/volunteer-dashboard',
    path: '/volunteer-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/memories': typeof MemoriesRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-passes': typeof AuthenticatedMyPassesRoute
  '/volunteer-dashboard': typeof AuthenticatedVolunteerDashboardRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/memories': typeof MemoriesRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/my-passes': typeof AuthenticatedMyPassesRoute
  '/volunteer-dashboard': typeof AuthenticatedVolunteerDashboardRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/gallery': typeof GalleryRoute
  '/live': typeof LiveRoute
  '/memories': typeof MemoriesRoute
  '/sponsors': typeof SponsorsRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/my-passes': typeof AuthenticatedMyPassesRoute
  '/_authenticated/volunteer-dashboard': typeof AuthenticatedVolunteerDashboardRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/memories'
    | '/sponsors'
    | '/volunteer'
    | '/admin'
    | '/my-passes'
    | '/volunteer-dashboard'
    | '/events/$slug'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/memories'
    | '/sponsors'
    | '/volunteer'
    | '/admin'
    | '/my-passes'
    | '/volunteer-dashboard'
    | '/events/$slug'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/donate'
    | '/gallery'
    | '/live'
    | '/memories'
    | '/sponsors'
    | '/volunteer'
    | '/_authenticated/admin'
    | '/_authenticated/my-passes'
    | '/_authenticated/volunteer-dashboard'
    | '/events/$slug'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  GalleryRoute: typeof GalleryRoute
  LiveRoute: typeof LiveRoute
  MemoriesRoute: typeof MemoriesRoute
  SponsorsRoute: typeof SponsorsRoute
  VolunteerRoute: typeof VolunteerRoute
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-passes': {
      id: '/_authenticated/my-passes'
      path: '/my-passes'
      fullPath: '/my-passes'
      preLoaderRoute: typeof AuthenticatedMyPassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/volunteer-dashboard': {
      id: '/_authenticated/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof AuthenticatedVolunteerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMyPassesRoute: typeof AuthenticatedMyPassesRoute
  AuthenticatedVolunteerDashboardRoute: typeof AuthenticatedVolunteerDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMyPassesRoute: AuthenticatedMyPassesRoute,
  AuthenticatedVolunteerDashboardRoute: AuthenticatedVolunteerDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  GalleryRoute: GalleryRoute,
  LiveRoute: LiveRoute,
  MemoriesRoute: MemoriesRoute,
  SponsorsRoute: SponsorsRoute,
  VolunteerRoute: VolunteerRoute,
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
